### ISSUE TITLE
Lifetime mismatch around .get()

### ISSUE THREAD

**Issue by chrysn** [jnqnfe/pulse-binding-rust#38] opened 2021-04-08 17:27 UTC
The PulseAudio API description of `pa_proplist_get` [says](https://www.freedesktop.org/software/pulseaudio/doxygen/proplist_8h.html#a33e88e1a023761e3bbfce9f127209274):

> The data pointer returned will point to an internally allocated buffer. The caller should make a copy of the data before the property list is accessed again.

However, the [get function](https://docs.rs/libpulse-binding/2.23.0/src/libpulse_binding/proplist.rs.html#318) has a signature of `pub fn get(&self, key: &str) -> Option<&[u8]>`, allowing safe Rust code to access the memory way after another access has happened.

The mismatch here is that get only takes a shared pointer, and thus limits the lifetime to as long as nothing "modifies" self, but the PA API already considers access a mutation.

I've found this tracking down why [myxer](https://github.com/Aurailus/Myxer) doesn't display the name of an (admittedly broken, but hey it's a cheap Bluetooth gadget, and the name is untrusted data after all) amplifier. I didn't run into trouble with this precisely (the fault I was looking for is somewhere else), and chances are the names *do* regularly point into memory isn't really mutated by later accesses, but the PA API doesn't guarantee it, and may change at any time.

Options as I see them are:
* Make `get` and anything else that "accesses" the proplist take a &mut self.
* Return an owned copy of the data.

I don't see any easy way to do either of them without breaking the API. Worse, the latter (which may sound easier on API users) would require locking for all accesses because Proplist implements Sync, so another thread could perform a get at the same time and copying the data out just before get returns would not be enough.

**Comment by jnqnfe** [comment] 2021-04-09 00:40
> The PulseAudio API description of `pa_proplist_get` [says](https://www.freedesktop.org/software/pulseaudio/doxygen/proplist_8h.html#a33e88e1a023761e3bbfce9f127209274):
> 
> > The data pointer returned will point to an internally allocated buffer. The caller should make a copy of the data before the property list is accessed again.
> 
> However, the [get function](https://docs.rs/libpulse-binding/2.23.0/src/libpulse_binding/proplist.rs.html#318) has a signature of `pub fn get(&self, key: &str) -> Option<&[u8]>`, allowing safe Rust code to access the memory way after another access has happened.

So firstly, per ['lifetime elision' rules](https://doc.rust-lang.org/reference/lifetime-elision.html), with this being a method, the lifetime of the reference within the return type is associated with the lifetime of the `self` reference, thus the result cannot outlive the immutable borrow of the `Proplist` object. This is perfectly in keeping with the documentation you quoted for the underlying C API function.

> The mismatch here is that get only takes a shared pointer, and thus limits the lifetime to as long as nothing "modifies" self, but the PA API already considers access a mutation.

I believe you're misunderstanding the documentation, which is understandable because it is expressed somewhat ambiguously. The get functions are just returning the pointers (and size in the generic case) held within the collection for the requested item. If an item is subsequently mutated then the data (pointer; size) previously returned may then be invalid. One 'get' call does not invalidate what was returned by a previous one, only a 'set' call may do so, and so it would for instance be perfectly fine to cycle through a set of items, getting references, then cycle through printing the data using them. There's only a potential problem if you mutate the collection and then try to use a previously obtained reference. This can be verified by checking out the code of the actual C API functions.

I don't believe that the documentation was ever meant to suggests that the functions may ever work in such a way that one get request invalidates a previous one. It is just a unfortunately poor description. I'm sure that the PA devs would welcome an improvement. The documentation on the corresponding function in my binding simply inherited that of the C API, and could also do with such an improvement.

I'll submit a patch to the PA devs to improve this text.

> I've found this tracking down why [myxer](https://github.com/Aurailus/Myxer) doesn't display the name of an (admittedly broken, but hey it's a cheap Bluetooth gadget, and the name is untrusted data after all) amplifier. I didn't run into trouble with this precisely (the fault I was looking for is somewhere else), and chances are the names _do_ regularly point into memory isn't really mutated by later accesses, but the PA API doesn't guarantee it, and may change at any time.

I'm afraid I'm rather lost and confused about this gadget name business, from what you have written here and in #39. Is this gadget name an invalid utf-8 string? From where is that being obtained? Is this invalid-utf8 string being stored within a `Proplist` somewhere? If so, then by what, Myxer or PA? If Myxer then there seems to be a failure to sanitize the string with a lossy conversion first, and perhaps you're incorrectly storing with `.set()` and reading with `.get_str()`? If PA, then is that the result of some bug in PA, or if PA may legitimately hand out such invalid strings, then perhaps there is a legitimate basis for me to add a `.get_str_lossy()` convenience method...

> Options as I see them are:
> 
> * Make `get` and anything else that "accesses" the proplist take a &mut self.
> 
> * Return an owned copy of the data.
>
> I don't see any easy way to do either of them without breaking the API. Worse, the latter (which may sound easier on API users) would require locking for all accesses because Proplist implements Sync, so another thread could perform a get at the same time and copying the data out just before get returns would not be enough.

Skipping most of this since it's based upon a flawed understanding as per above...

The fact of `Proplist` implementing `Sync` being problematic in multi-threading is a perfectly legitimate concern. The problem is that I'm trying to offer an efficient zero-cost layer to PA, whilst wrangling with the significant complication of supporting multiple programming models of standard-mainloop, threaded-mainloop and glib-mainloop.

Under the threaded-mainloop model the mainloop lock must be used to control access to anything shared between the user thread(s) and the background mainloop thread. Use of `Proplist` objects whenever shared across multiple user threads, or shared with a callback (which would be asynchronously executed in the mainloop thread) must be done behind the mainloop lock (one used solely within a single thread you may be able to use without the lock held). Within this environment (the most common one), `Proplist` being `Sync` makes perfect sense, since the external mainloop lock, when used correctly, provides the thread safety, and lack of `Sync` would force users to add an unnecessary `Arc` wrapper.

Under the standard-mainloop model, there is no mainloop lock, because you're controlling the mainloop within your user thread. If you have multiple user threads, then you would need to add an `Arc` wrapper around the `Proplist` (or type containing it) in order to use it safely. It is unfortunate that having `Sync` for the threaded-mainloop case makes it possible for users to use these objects unsafely.

I'm not happy about this situation regarding `Sync`. It's an example of the imperfections resulting from the difficulties arising from supporting multiple mainloop designs without significantly duplicating stuff.

I'll add a comment to the documentation regarding this though.

---

I'm going to close this upon the basis that:
 - The initial things you point out are based upon a misunderstanding of the meaning of the C API documentation.
 - The `Sync` issue is a "known, by design" type of deficiency and not something that can practically be fixed without some hypothetical major redesign. There are multiple easy mistakes users can make using this library that are unfortunate and not practical to do anything about without some radical redesign. It is one of the most important items on the to-do list to try to find a good way to resolve this stuff someday. It's rather pointless keeping this issue open for it though.
 - The issue of the amplifier name not showing up in Myxer is an entirely separate issue.

Though:
 - Feel free to respond. :)
 - Feel free to open up a new issue regarding the problem of the amplifier name not showing up in Myxer if you wish.

**Closed by jnqnfe** 2021-04-09 00:40 UTC

**Comment by chrysn** [comment] 2021-04-09 07:18
> I believe you're misunderstanding the documentation, which is
> understandable because it is expressed somewhat ambiguously.

Yes, that'd be the key point -- if as you describe it PA will, inside a
proplist, always have all the values allocated for as long as the
proplist is around, the lifetimes are all perfectly good.

(I'm sensitized here because I'm providing a similar API around the
coap-message crate, and while *most* of the implementations there have
their properties backed by longliving memory, implementers of the trait
are at leisure to store some data differently (say, in a u32) and only
serialize them to the big-endian buffer that was requested for the time
of an access.)

> I'll submit a patch to the PA devs to improve this text.

Thanks, that's a resolution path to this issue that I've missed
("Make PA promise to not do this"), and yes, it's probably the best one
:-)

Please leave a link here; while I won't have anything to contribute I'm
still curious to follow it.

> I'm afraid I'm rather lost and confused about this gadget name
> business, from what you have written here and in #39. Is this gadget
> name an invalid utf-8 string?

It was *actually* https://github.com/Aurailus/Myxer/pull/11 where Myxer
only accessed device.description and didn't fall back to device.alias or
device.name. By the time I was digging through pulse-binding-rust I only
kjnew that the channel's name was weird (only saw it in GUIs, never in
hexdump); by now I've learned it just contains a newline at the end. I
can't easily try out yet what'd happen if the Bluetooth device
advertised itself with a non-UTF8 name.

> The fact of `Proplist` implementing `Sync` being problematic in
> multi-threading is a perfectly legitimate concern.

... but in the light of "Proplist may promise to only return memory
inside itself", I don't see anything wrong with it.

Thanks for your detailed response!

**Comment by jnqnfe** [comment] 2021-04-09 19:31
> I'll submit a patch to the PA devs to improve this text.
> Thanks, that's a resolution path to this issue that I've missed ("Make PA promise to not do this"), and yes, it's probably the best one :-) Please leave a link here; while I won't have anything to contribute I'm still curious to follow it.

[MR](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/536)

I initially emailed it to the mailing list, but today discovered that they'd migrated to gitlab a couple of years ago. Not being subscribed to the list, and not having needed to submit a patch for some time, I'd completely missed that. :D

>> I'm afraid I'm rather lost and confused about this gadget name business, from what you have written here and in #39. Is this gadget name an invalid utf-8 string?
>
> It was *actually* [Aurailus/Myxer#11](https://github.com/Aurailus/Myxer/pull/11) where Myxer only accessed device.description and didn't fall back to device.alias or device.name. By the time I was digging through pulse-binding-rust I only kjnew that the channel's name was weird (only saw it in GUIs, never in hexdump); by now I've learned it just contains a newline at the end. I can't easily try out yet what'd happen if the Bluetooth device advertised itself with a non-UTF8 name.

Ok.
